"""Runtime enforcement of the "holdout touched once" hard rule.

Two independent layers, defense-in-depth:

1. Caller-identity gate (`check_caller`): only a module literally named
   `final_evaluation.py` may request the "holdout" split from
   `data/storage.py::load_split`.
2. Data-boundary gate (`enforce_dataframe_boundary`): even if a dataframe
   was constructed by some other means (e.g. someone manually slices a raw
   Parquet file), any dataframe whose timestamps reach past a symbol's
   holdout boundary raises when passed into the engine/optimizer/gates
   unless the caller explicitly (and rarely) passes allow_holdout=True.
"""

from __future__ import annotations

import inspect
from pathlib import Path

import pandas as pd
import yaml

_FINAL_EVAL_FILENAME = "final_evaluation.py"


class HoldoutBreachError(Exception):
    """Raised when code outside evaluation/final_evaluation.py tries to read
    or process data past the holdout boundary."""


def _load_boundaries(holdout_path: str | Path) -> dict:
    holdout_path = Path(holdout_path)
    if not holdout_path.exists():
        raise FileNotFoundError(
            f"{holdout_path} does not exist yet — it is generated by data/splits.py "
            "after real historical data has been fetched (see config/holdout.yaml.template "
            "and bot/FINDINGS.md for why that hasn't happened in this session)."
        )
    with open(holdout_path) as f:
        return yaml.safe_load(f)["splits"]


def check_caller(split: str, stack_offset: int = 2) -> None:
    """Raise HoldoutBreachError if `split == "holdout"` and the immediate
    caller of the function that invoked this (e.g. load_split) is not
    evaluation/final_evaluation.py.

    stack_offset=2 by default: frame 0 is this function, frame 1 is the
    library function that called us (e.g. load_split), frame 2 is whoever
    called that library function — the party we actually want to identify.
    """
    if split != "holdout":
        return
    stack = inspect.stack()
    if stack_offset >= len(stack):
        raise HoldoutBreachError("could not determine caller for holdout split request")
    caller_file = Path(stack[stack_offset].filename).name
    if caller_file != _FINAL_EVAL_FILENAME:
        raise HoldoutBreachError(
            f"holdout split requested from '{caller_file}' — only "
            f"{_FINAL_EVAL_FILENAME} is permitted to read holdout data. "
            "The holdout set is touched once, per the hard rules."
        )


def enforce_dataframe_boundary(
    df: pd.DataFrame,
    symbol: str,
    timeframe: str,
    allow_holdout: bool = False,
    holdout_path: str | Path = "config/holdout.yaml",
    timestamp_col: str = "timestamp",
) -> None:
    """Raise HoldoutBreachError if `df` contains any bar at or past the
    holdout boundary (val_end) for this symbol/timeframe, unless
    allow_holdout=True was explicitly passed (only final_evaluation.py
    should ever do that)."""
    if df.empty:
        return
    boundaries = _load_boundaries(holdout_path)
    try:
        val_end = pd.Timestamp(boundaries[symbol][timeframe]["val_end"])
    except KeyError as exc:
        raise HoldoutBreachError(
            f"no holdout boundary configured for {symbol}/{timeframe} in {holdout_path}"
        ) from exc
    max_ts = pd.Timestamp(df[timestamp_col].max())
    if max_ts.tzinfo is None:
        max_ts = max_ts.tz_localize("UTC")
    if val_end.tzinfo is None:
        val_end = val_end.tz_localize("UTC")
    if not allow_holdout and max_ts >= val_end:
        raise HoldoutBreachError(
            f"dataframe for {symbol}/{timeframe} extends to {max_ts} which is at/past "
            f"the holdout boundary {val_end}. Only evaluation/final_evaluation.py may "
            "pass allow_holdout=True."
        )
